name: Selenium Tests

on: [push]

env:
  USER: ${{ secrets.USER }}
  PASS: ${{ secrets.PASS }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Selenium tests
        run: |
          python main.py

      - name: Commit Changes during Workflow
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Uploaded new episode
